### ISSUE TITLE
How to exclude multiple files from algolia index

### ISSUE THREAD

**Issue by chel-007** [lukeocodes/netlify-plugin-algolia-index#2]
Hello luke,, I tried using your plugin for my website,, I actually works great. I wanted to understand better how i can exclude particular files or folders from the indexing. In your setup you gave an example like this:
[[plugins]]
package = 'netlify-plugin-algolia-index'
# all inputs is optional, we just show you the defaults below
# [plugins.inputs]
# exclude = ['/404.html'] # don't index this file
So,, then the 404.html should be excluded. I wanted to do this on multiple files. I tried something like this : # exclude = ['/404.html','downloads','blog','privacy','staff'] and after downloading the json file at the generated url,, i uploaded it to algolia,, and I was still getting those excluded files in the search results. Perhaps the commas shouldn't be used as the separator? . I would be greatful if you can assist to achieve it . Thanks, chel

**Comment by lukeocodes** [comment]
So I would prefix the directories with / and make them regexes.

Using a literal string in TOML for regex is done with three '.

For example, this is my TOML config right now, so that I ignore all files in `/admin` and `/search`. 

```
[[plugins]]
  package = "netlify-plugin-algolia-index"
    [plugins.inputs]
      exclude = ['''^\/admin.*''', '''^\/search.*''']
```

Please note, I have a new version to publish that will integrate directly with Algolia's API without producing an index file. See #1 for more info
